### ISSUE TITLE
endpoint_configuration with null endpoint_id

### ISSUE THREAD

**Issue by galshmil** [clowdhaus/terraform-aws-global-accelerator#11]
## Description

When using the module with endpoint_configuration block inside, I expect the module to skip it when I pass a null `endpoint_id`, but instead it tries to create the endpoint_configuration and fails with getting a non-null `endpointId` error.
This is problematic when trying to create GlobalAccelerators without any endpoint behind.

## Versions

- Module version [Required]: 2.2.0

- Terraform version: 1.4.5

- Provider version(s): aws 5.30.0

## Reproduction Code [Required]

```
module "global_accelerator" {
  source  = "terraform-aws-modules/global-accelerator/aws"
  version = "~> 2.2.0"

  name = "main"

  listeners = {
    listener_1 = {
      endpoint_group = {
        endpoint_configuration = [{
          endpoint_id = null
        }]
      }

      port_ranges = [
        {
          from_port = 443
          to_port   = 443
        }
      ]
      protocol = "TCP"
    }
  }
}
```

## Expected behavior

A new global accelerator is created, with listener and endpoint group but without any endpoint in the group.
Module is skipping the use of endpoint configuration block and no error is produced.

## Actual behavior

The module still tries to create an endpoint configuration block and end up with the following error:
```
│ Error: updating Global Accelerator Endpoint Group (arn:<DEDUCTED>): InvalidArgumentException: EndpointConfiguration endpointId must not be null or empty.
│ 
│   with module.global_accelerator["main"].aws_globalaccelerator_endpoint_group.this["listener_1"],
│   on .terraform/modules/global_accelerator/main.tf line 55, in resource "aws_globalaccelerator_endpoint_group" "this":
│   55: resource "aws_globalaccelerator_endpoint_group" "this" {
```

## Additional context

I do see there is some check already based on `endpoint_id`, but it seems to fail to catch it when null is passed.
https://github.com/terraform-aws-modules/terraform-aws-global-accelerator/blob/038b9cd3c2d6e2fb70e6af517b4fc4467206e50b/main.tf#L69C97-L69C108

**Comment by bryantbiggs** [comment]
thats not valid - if you are providing a value then the Terraform is going to try to use it which `null` is not valid in this context. the `can()` is simply a check for if the key exists - if the key exists then its going to try to create the resource

**Comment by galshmil** [comment]
> thats not valid - if you are providing a value then the Terraform is going to try to use it which `null` is not valid in this context. the `can()` is simply a check for if the key exists - if the key exists then its going to try to create the resource

I understand.
Won't it make more sense than to add additional check next to the `can()` to validate `endpoint_id` is not null as dependency for `endpoint_configuration`?

`... can(e.endpoint_id) && e.endpoint_id != null ...`

**Comment by bryantbiggs** [comment]
no - if you don't want to configure the endpoint configuration, don't pass a value to `endpoint_configuration`
