### ISSUE TITLE
Endpoint Group gets created even when the listener's endpoint_group is not defined

### ISSUE THREAD

**Issue by alex-bako** [clowdhaus/terraform-aws-global-accelerator#13]
## Description

`globalaccelerator_endpoint_group` get's created even when the listener's `endpoint_group` is empty or not defined.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: **2.2.0**

- Terraform version:
```bash
➜ terraform -version
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/gitlabhq/gitlab v15.11.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0

Your version of Terraform is out of date! The latest version
is 1.7.5. You can update by downloading from https://www.terraform.io/downloads.html
```
- Provider version(s):
```bash
➜ terraform providers -version
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/gitlabhq/gitlab v15.11.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0

Your version of Terraform is out of date! The latest version
is 1.7.5. You can update by downloading from https://www.terraform.io/downloads.html
```

## Reproduction Code [Required]

```terraform
module "global_accelerator" {
  source  = "terraform-aws-modules/global-accelerator/aws"
  version = "2.2.0"

  name = "my-global-accelerator"

  flow_logs_enabled   = false
  flow_logs_s3_bucket = "logs"
  flow_logs_s3_prefix = "flow-logs/accelerator"

  listeners = {
    backend = {
      client_affinity = "SOURCE_IP"

      port_ranges = [
        {
          from_port = 80
          to_port   = 80
        },
        {
          from_port = 443
          to_port   = 443
        }
      ]

      protocol = "TCP"
    }
  }
}
```

- Try to create an Accelerator and a Listener resource. Do not provide the `endpoint_group` property for the listener, and it will try to create the endpoint group anyways.

## Expected behavior

- No endpoint group should be created in this scenario

## Actual behavior

- Terraform tries to create an endpoint group

### Terminal Output Screenshot(s)

- N/A

## Additional context

- We're using Terragrunt, and the `Accelerator` and `Listener` resources are created as part of the global setup, however the `Endpoint Group` resources should be created for each region in a later step of the process.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.2.2 :tada:
